Starter Application Setup
realtimschmidt/bloc-chat pull request #1
Opened 2017-03-23 13:37 UTC by realtimschmidt

@droberts84
Hi David, 

I completed the Bloc Starter Application workflow for BlocChat.
index.html should now connect to Angular, AngularFire and Firebase.

2017-03-23 22:25 UTC, drobtravels requested changes
All good other that the comments I made

2017-03-23 22:25 UTC, droberts84 commented on app/pages/index.html
> +    <script src="https://cdn.firebase.com/libs/angularfire/2.0.1/angularfire.min.js"></script>
Angular Fire should be after Firebase, since its really just a wrapper for Firebase

2017-03-23 22:25 UTC, droberts84 commented on app/pages/index.html
> +    <script src="https://www.gstatic.com/firebasejs/3.7.3/firebase.js"></script>
You may want to use 3.6.6 due to [this issue](https://github.com/firebase/angularfire/issues/922)  I'm not sure if its been resolved in 3.7.3

2017-03-24 01:22 UTC, realtimschmidt commented on app/pages/index.html
> +    <script src="https://www.gstatic.com/firebasejs/3.7.3/firebase.js"></script>
Whoa. That's a big issue. I'll make the change to 3.6.6

2017-03-24 01:26 UTC, realtimschmidt commented on app/pages/index.html
> +    <script src="https://cdn.firebase.com/libs/angularfire/2.0.1/angularfire.min.js"></script>
I hear what your saying. I'll make the update. 
Check out the instructions from Bloc. About half way down the page, it shows Angular, AngularFire, and Firebase in this order.

https://www.bloc.io/resources/getting-started-with-frontend-projects

2017-03-24 01:28 UTC, merged